export const FIELD_TYPES = [
  { value: "text", label: "Text" },
  { value: "textarea", label: "Textarea" },
  { value: "number", label: "Number" },
  { value: "email", label: "Email" },
  { value: "password", label: "Password" },
  { value: "date", label: "Date" },
  { value: "time", label: "Time" },
  { value: "checkbox", label: "Checkbox" },
  { value: "radio", label: "Radio" },
  { value: "dropdown", label: "Dropdown" },
  { value: "file", label: "File Upload" },
  { value: "range", label: "Range" },
  { value: "color", label: "Color" },
  { value: "tel", label: "Telephone" },
  { value: "url", label: "URL" },
  { value: "hidden", label: "Hidden" },
  { value: "section", label: "Section" },
  { value: "heading", label: "Heading" },
  { value: "p", label: "Paragraph" },
  { value: "button", label: "Button" },
  { value: "submit", label: "Submit Button" },
  { value: "reset", label: "Reset Button" },
  { value: "captcha", label: "Captcha" },
  { value: "signature", label: "Signature" },
  { value: "rating", label: "Rating" },
  { value: "matrix", label: "Matrix" },
  { value: "table", label: "Table" },
  { value: "map", label: "Map" },
  { value: "video", label: "Video" },
  { value: "separator", label: "Separator" },
];
